services:
  backend:
    build:
      context: .
      target: development
    init: true
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules
    stop_grace_period: 10s

volumes:
  backend_node_modules:
